version: '3.8'
services:
  booking-service:
    image: booking-service:0.0.1
    environment:
      BOOKING_CLIENT_PORT: 8881
    build:
      context: .
      dockerfile: booking-service\Dockerfile
    ports:
      - "8881:8881"


  telegram-bot:
    image: telegram-bot:0.0.1
    depends_on:
      - booking-service
    build:
      context: .
      dockerfile: telegram-bot\Dockerfile
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_BOT_BOOKING_CONNECT: booking-service:8881

#  db:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5434:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
#volumes:
#  db:
#    driver: local

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    restart: unless-stopped
